'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.34014
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("代理连接管理.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  使用此强类型资源类，为所有资源查找
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 The proxy address or proxy port was mistake 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property frmAddProxy_error() As String
            Get
                Return ResourceManager.GetString("frmAddProxy_error", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Can&apos;t change 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property frmMain_canceloruncomp() As String
            Get
                Return ResourceManager.GetString("frmMain_canceloruncomp", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Close the proxy before exit? 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property frmMain_closeproxy() As String
            Get
                Return ResourceManager.GetString("frmMain_closeproxy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Exit 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property frmMain_exit() As String
            Get
                Return ResourceManager.GetString("frmMain_exit", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 You sure to exit? 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property frmMain_exitcomfirm() As String
            Get
                Return ResourceManager.GetString("frmMain_exitcomfirm", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 The proxy is using 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property frmMain_proxyisusing() As String
            Get
                Return ResourceManager.GetString("frmMain_proxyisusing", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 The data is not enough to add a new item 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property frmMain_uncomplete() As String
            Get
                Return ResourceManager.GetString("frmMain_uncomplete", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property green() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("green", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property main() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("main", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Proxy Disabled 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property mdTPLM_disabled() As String
            Get
                Return ResourceManager.GetString("mdTPLM_disabled", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Disable Proxy 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property mdTPLM_disableproxy() As String
            Get
                Return ResourceManager.GetString("mdTPLM_disableproxy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Proxy :  的本地化字符串。
        '''</summary>
        Friend ReadOnly Property mdTPLM_head_proxy() As String
            Get
                Return ResourceManager.GetString("mdTPLM_head_proxy", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似  is enable 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property mdTPLM_last_enable() As String
            Get
                Return ResourceManager.GetString("mdTPLM_last_enable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Current Setting :  的本地化字符串。
        '''</summary>
        Friend ReadOnly Property mdUI_current() As String
            Get
                Return ResourceManager.GetString("mdUI_current", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 [Disable] 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property mdUI_disable() As String
            Get
                Return ResourceManager.GetString("mdUI_disable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 [Enable] 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property mdUI_enable() As String
            Get
                Return ResourceManager.GetString("mdUI_enable", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 None 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property mdUI_none() As String
            Get
                Return ResourceManager.GetString("mdUI_none", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property new64px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("new64px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似于 (Icon) 的 System.Drawing.Icon 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property red() As System.Drawing.Icon
            Get
                Dim obj As Object = ResourceManager.GetObject("red", resourceCulture)
                Return CType(obj,System.Drawing.Icon)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property uptodate64px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("uptodate64px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property wait64px() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("wait64px", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
